### ISSUE TITLE
how can we use it?

### ISSUE THREAD

**Issue by Dishendramishra** [ivh/PyReduce#3]
Can you please show how it can be used to process fits format files?

**Comment by AWehrhahn** [comment]
Sorry, it took so long to answer.
I recommend to use my fork of the project https://github.com/AWehrhahn/PyReduce, as its is much further ahead in development (and yes I worked with Thomas in this).

In the examples folder you will uves_example.py (and a few others, but that one is the easiest as it will download the required datafiles as well). Try running that one, to see what happens with the fits files.
